/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"

int calculateFactorial(int fact){
	if(fact <0){
		return 0;
	}
	int result = 1;
	for(int i=1;i<=fact;i++){
		result*=i;
	}
	return result;
}

int *
factorial_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Calculating Factorial of %d ...\n",argp->fact);
	result = calculateFactorial(argp->fact);
	printf("Done\n");

	return &result;
}
