/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chat.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Message *
chat_1(argp, clnt)
	Message *argp;
	CLIENT *clnt;
{
	static Message clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, chat, xdr_Message, argp, xdr_Message, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
