/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATETIME_H_RPCGEN
#define _DATETIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TIME_PROG 0x1231231
#define TIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define dateTime 1
extern  long * datetime_1(void *, CLIENT *);
extern  long * datetime_1_svc(void *, struct svc_req *);
extern int time_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define dateTime 1
extern  long * datetime_1();
extern  long * datetime_1_svc();
extern int time_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATETIME_H_RPCGEN */
