/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct Message {
	char message[100];
};
typedef struct Message Message;
#ifdef __cplusplus
extern "C" bool_t xdr_Message(XDR *, Message*);
#elif __STDC__
extern  bool_t xdr_Message(XDR *, Message*);
#else /* Old Style C */
bool_t xdr_Message();
#endif /* Old Style C */


#define CHAT_PROG ((rpc_uint)0x1231231)
#define CHAT_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define chat ((rpc_uint)1)
extern "C" Message * chat_1(Message *, CLIENT *);
extern "C" Message * chat_1_svc(Message *, struct svc_req *);

#elif __STDC__
#define chat ((rpc_uint)1)
extern  Message * chat_1(Message *, CLIENT *);
extern  Message * chat_1_svc(Message *, struct svc_req *);

#else /* Old Style C */
#define chat ((rpc_uint)1)
extern  Message * chat_1();
extern  Message * chat_1_svc();
#endif /* Old Style C */

#endif /* !_CHAT_H_RPCGEN */
