/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dateTime.h"
#include<time.h>

void
time_prog_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	char *datetime_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TIME_PROG, TIME_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = datetime_1((void*)&datetime_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{


	char dateTimeBuffer[100];
    strftime (dateTimeBuffer, 100, "%d-%m-%M %H:%M:%S", localtime (result_1));

	printf("Time on host : %s is :\n\t%s , ( %s )\n", host , dateTimeBuffer , ctime(result_1));
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	time_prog_1 (host);
exit (0);
}
